
[toolchain]
[features]
resolution = true
skip-lint = false

[programs.mainnet]
pump_meteora = "9MHPjXpZXgJrB4NiJVFStE5qy7Nqp7yaYpaqNe5jNfMw"

[programs.devnet]
pump_meteora = "9MHPjXpZXgJrB4NiJVFStE5qy7Nqp7yaYpaqNe5jNfMw"

[programs.localnet]
pump_meteora = "9MHPjXpZXgJrB4NiJVFStE5qy7Nqp7yaYpaqNe5jNfMw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "./keys/*.json"

[scripts]
build = "rm -rf target && anchor build && mkdir -p target/deploy && cp ./keys/program/*.json ./target/deploy/pump_meteora-keypair.json"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
